name: Issue Digest

on:
  schedule:
    - cron: '10 * * * *'  # runs once at 00:00 daily

jobs:
  issue-digest:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      
    steps:
      - name: Run Issue Digest Action
        uses: nus-oss/GithubDigest@master
        with:
          repo: "teammates/TEAMMATES"
          timezone: "Singapore"
