name: Issue Digest

on:
  schedule:
    - cron: '0 0 * * *'  # runs once at 00:00 daily

jobs:
  issue-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Run Issue Digest Action
        uses: Eclipse-Dominator/Github_Digest@master
